Topic1
Marcosgreppi/startup pull request #2
Opened 2016-10-12 19:54 UTC by Marcosgreppi

2016-10-13 18:35 UTC, afiorenza requested changes
Several changes needed

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-1.js
> +    let response = JSON.parse(event.target.response);
This will blow up if the request state is not DONE.

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-1.js
> +        document.getElementById("buttonJoke").innerHTML  = xhttp.responseText.value.joke;
We are you doing this? The idea was to set the joke a section not in a button

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-1.js
> +    xhttp.open("GET", object.url);
HTTP method should be in the configuration parameter... There are others methods you can use here

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-1.js
> + this.methodHttp = methodHttp;
Add variables to window object is not a good practice. As we talk yesterday about scopes. Please refactor this.

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-2.js
> +  console.log(matrix);
Remember to remove console.log's

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/ex12.html
> +    <style>
This should go in the stylesheet

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/ex12.html
> +    <button onclick="importMatrix(matrix)" id="importmatrixbutton" type="buttonimportmatrix" name="buttonimportmatrix">Import</button>
I see several errors here:

- `buttonimportmatrix` is not a type of button. You can find type of buttons here http://www.w3schools.com/tags/att_button_type.asp

- `onclick="importMatrix(matrix)"` pass this parameter here is wrong. You should have the matrix as a variable inside the function 

- `Import` is not a good text for the button. It is very general and could be any action

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/ex12.html
> +  <body onload="Matrix()">
Why are you doing this here?

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +    <label for="Search"><input type="text"input type="text" name="searcher" id="searcher" value=""/>
</label> missing

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +    <div>
Why do you leave this `div` empty?

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +    <button type="button" id="buttonReusableJoke"onclick="ReusableJoke ()">ReusableJokeConfig</button>
Missing space between `"` and `onClick`

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +    <button type="button" id="buttonReusableJoke"onclick="ReusableJoke ()">ReusableJokeConfig</button>
Also space between `ReusableJoke` and `()` is not needed

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +
Tag `<section>` missing here

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +
You shouldn't leave any break line here

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-2.js
> +  for(var indexTR = 0; indexTR < 3; indexTR++ ){
You could use `map` function here

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-2.js
> +    for (var indexTD = 0; indexTD < 3; indexTD++) {
You could use `map` function here

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-2.js
> +    var trNode = document.createElement("tr");
The guide says we should always use let instead var. Also every variable declaration should go outside loop in order to make this function more perfomant and avoid declaration several times.

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/style1-1.css
> +    background-color:grey;
Remember to leave a space after `:`

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-1.js
> +      var columnNode = document.createElement("li");
For performance issues, the variable declarations should go outside the loop

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-1.js
> +      var columnNode = document.createElement("li");
For performance issues, the variable declarations should go outside the loop

2016-10-13 18:35 UTC, afiorenza commented on 01-JS-DOM-APIs/1-1.js
> +  let objconfig = new config ("GET", "https://api.github.com/search/repositories?q=javascript", true);
Why you are calling new operator here? also assign it to a variable if in the function you are setting the configuration to the window

2016-10-13 18:54 UTC, Marcosgreppi commented on 01-JS-DOM-APIs/index.html
> +    <div>
I left it empty so the field for the FreeSearch is not on the same line that the QSearch and the list for both gets generated under the FreeSearch

2016-10-17 17:22 UTC, Marcosgreppi commented
Fixed everything, pushing right now

2016-10-19 18:49 UTC, Marcosgreppi commented on 01-JS-DOM-APIs/ex12.html
> +    <style>
fixed

2016-10-19 18:50 UTC, Marcosgreppi commented on 01-JS-DOM-APIs/index.html
> +
fixed

2016-10-20 19:38 UTC, afiorenza approved these changes

2016-10-24 17:02 UTC, merged