Topic2
Marcosgreppi/startup pull request #3
Opened 2016-10-19 18:49 UTC by Marcosgreppi

2016-10-19 19:02 UTC, afiorenza requested changes
A few changes. Also next time you should branch from master because here i can see code that is not from this topic. Also where is package.json? You must upload it too.

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.html
> +
This break line is not needed

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.html
> +
Same here

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.js
> +let Social = {
You could move this to another file

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.js
> +  movie1.play();
Try to register an event in the event-emiter

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.js
> +  movie2.play();
Movie 2 is not defined...

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.js
> +  console.log(movie1.title);
How this work as movie1 is not defined?

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.js
> +    console.log("share", this.title, "with", friendName)
Use es6 template string here

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/2-1.js
> +    console.log(friendName, "likes", this.title)
Same here

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/classEventEmitter.js
> +    if (this.listeners[event] != callback) {
Use `!==` as it is more strict

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/classLogger.js
> +     console.log(movieExecute.title + ' ' + functionName)
Use es6 template strings here

2016-10-19 19:02 UTC, afiorenza commented on 02-oop-inheritance/classMovie.js
> +    this.actors = this.actors.concat(newActors);
Initialize this attribute in the class

2016-10-19 19:54 UTC, Marcosgreppi commented on 02-oop-inheritance/2-1.html
> +
removed

2016-10-19 19:55 UTC, Marcosgreppi commented on 02-oop-inheritance/2-1.html
> +
removed

2016-10-19 19:55 UTC, Marcosgreppi commented on 02-oop-inheritance/2-1.js
> +  console.log(movie1.title);
fixed, changed name at the last minute forgot about the rest

2016-10-19 19:55 UTC, Marcosgreppi commented on 02-oop-inheritance/2-1.js
> +  movie2.play();
fixed, changed name at the last minute forgot about the rest

2016-10-19 19:55 UTC, Marcosgreppi commented on 02-oop-inheritance/2-1.js
> +let Social = {
moved

2016-10-19 19:55 UTC, Marcosgreppi commented on 02-oop-inheritance/2-1.js
> +    console.log("share", this.title, "with", friendName)
fixed

2016-10-19 19:55 UTC, Marcosgreppi commented on 02-oop-inheritance/2-1.js
> +    console.log(friendName, "likes", this.title)
fixed

2016-10-19 19:55 UTC, Marcosgreppi commented on 02-oop-inheritance/classEventEmitter.js
> +    if (this.listeners[event] != callback) {
fixed

2016-10-19 19:56 UTC, Marcosgreppi commented on 02-oop-inheritance/classLogger.js
> +     console.log(movieExecute.title + ' ' + functionName)
fixed

2016-10-19 19:58 UTC, Marcosgreppi commented on 02-oop-inheritance/classMovie.js
> +    this.actors = this.actors.concat(newActors);
changed

2016-10-20 19:40 UTC, afiorenza requested changes
Template strings are not well implemented. Check this documentation https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals

2016-11-14 13:49 UTC, afiorenza approved these changes

2016-11-14 17:06 UTC, merged