Topic4
Marcosgreppi/startup pull request #4
Opened 2016-10-24 20:24 UTC by Marcosgreppi

2016-10-25 14:48 UTC, afiorenza requested changes
Good job! just a few changes

2016-10-25 14:48 UTC, afiorenza commented on 04-HTML5-APIs/4-1.js
> +  writeToScreen("<span style="color: red;">ERROR:</span> " + evt.data);
The style should go on a css file.

2016-10-25 14:48 UTC, afiorenza commented on 04-HTML5-APIs/4-1.js
> +  websocket.onopen = function(evt) { onOpen(evt) };
it is not necessary to declare a function to just call a function. You could directly call onOpen function. The same with following lines.

2016-10-25 14:48 UTC, afiorenza commented on 04-HTML5-APIs/4-1.js
> +function onOpen(evt) {
`evt` is not a descriptive name. Please refactor this.

2016-10-25 14:48 UTC, afiorenza commented on 04-HTML5-APIs/4-1.js
> +  writeToScreen("<span style="color: blue;">RESPONSE: " + evt.data+"</span>");
The style should go on a css file. Also you could use template literals.

2016-10-25 14:48 UTC, afiorenza commented on 04-HTML5-APIs/4-1.js
> +  let pre = document.createElement("p");
What is pre? Refactor this with a more descriptive name.

2016-10-25 14:48 UTC, afiorenza commented on 04-HTML5-APIs/4-1.js
> +  pre.style.wordWrap = "break-word";
Style should go on css file.

2016-10-25 14:48 UTC, afiorenza commented on 04-HTML5-APIs/4-2.js
> +  console.log(document.getElementById('canvas'))
Remember to remove console.logs. Are just for debugging.

2016-10-25 18:48 UTC, Marcosgreppi commented on 04-HTML5-APIs/4-1.js
> +function onOpen(evt) {
fixed

2016-10-25 19:06 UTC, Marcosgreppi commented on 04-HTML5-APIs/4-2.js
> +  console.log(document.getElementById('canvas'))
fixed

2016-10-26 16:54 UTC, Marcosgreppi commented on 04-HTML5-APIs/4-1.js
> +  websocket.onopen = function(evt) { onOpen(evt) };
fixed

2016-10-26 17:18 UTC, Marcosgreppi commented on 04-HTML5-APIs/4-1.js
> +  let pre = document.createElement("p");
fixed

2016-11-14 13:49 UTC, afiorenza approved these changes

2016-11-14 17:07 UTC, merged